filebeat.inputs:
- type: docker
  containers:
    ids:
      - "*"
    path: "/var/run/docker.sock"
  combine_partial: true
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

logging.json: true